-- Boutiques Ooredoo reelles depuis boutique_actif.xls
-- Genere automatiquement par generate_full_data.py

BEGIN;

-- Supprimer les anciennes boutiques (attention aux FK)
-- INSERT avec ON CONFLICT pour ne pas casser les FK existantes

INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I08', 'Boutique KSAR HLEL', 'SOUSSE', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M21', 'Boutique CARREFOUR', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I24', 'Boutique HAMMAM LIF', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I03', 'Boutique ENNASR', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M19', 'Boutique AEROPORT MONASTIR', 'MONASTIR', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M20', 'Boutique KASSERINE', 'KASSERINE', 'Centre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M22', 'Boutique SILIANA', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I19', 'Boutique LE KEF', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I20', 'Boutique SOUSSE ERRIADH', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('C01', 'Boutique CHARGUIA', 'CHARGUIA 1', 'Autre', 'Ben Ghorbel Ahmed', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M01', 'Boutique ZEPHYR', 'La Marsa', 'Grand Tunis', 'Ben Amor Hichem', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M02', 'Boutique MEDINA PALACE', 'Tunis', 'Grand Tunis', 'Jami Zeinab', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M03', 'Boutique SFAX I', 'SFAX', 'Sud', 'Chiha Moez', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M04', 'Boutique SOUSSE', 'Sousse', 'Sahel', 'Ben Ameur Lamia', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('G01', 'CENTRE CORPORATE', 'La Charguia', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('R01', 'CENTRE RECOUVREMENT', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M18', 'Boutique LAC', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('S01', 'Boutique ZARZIS', 'ZARZIS', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M16', 'Boutique MAHDIA', 'MAHDIA', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M17', 'Boutique MONASTIR', 'MONASTIR', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I01', 'Boutique HAMMAMET', 'HAMMAMET', 'Cap Bon', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M05', 'Boutique BARDO', 'TUNIS', 'Grand Tunis', 'ZYDOUNE', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M06', 'Boutique NABEUL', 'NABEUL', 'Cap Bon', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M07', 'Boutique BIZERTE', 'BIZERTE', 'Nord', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M08', 'Boutique ARIANA', 'ARIANA', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M09', 'Boutique EZZAHRA', 'EZZAHRA', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M10', 'Boutique AEROPORT', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M13', 'Boutique GABES', 'GABES', 'Sud', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M14', 'Boutique SFAX II', 'SFAX', 'Sud', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M15', 'Boutique BEJA', 'BEJA', 'Nord', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M11', 'Boutique KAIROUAN', 'KAIROUAN', 'Centre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('M12', 'Boutique GAFSA', 'GAFSA', 'Sud-Ouest', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I07', 'Boutique LE KRAM', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I04', 'Boutique MSAKEN', 'SOUSSE', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I10', 'Boutique SOUSSE KHEZAMA', 'SOUSSE', 'Sahel', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I09', 'Boutique KELIBIA', 'KELIBIA', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I11', 'Boutique MEDENINE', 'MEDENINE', 'Sud', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('T01', 'SHOP MOBILE 1', 'MOBILE', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I21', 'Boutique MANNOUBA', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I23', 'Boutique TOZEUR', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I02', 'Boutique EL MOUROUJ', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I05', 'Boutique SFAX 5 AOUT', 'SFAX', 'Sud', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I06', 'Boutique ETTADHAMEN', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I12', 'Boutique KEBILI', 'KEBILI', 'Sud-Ouest', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I13', 'Boutique MENZAH 6', 'MENZAH 6', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I14', 'Boutique JENDOUBA', 'JENDOUBA', 'Nord', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I15', 'Boutique AL JAZIRA', 'AL JAZIRA', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I16', 'Boutique JERBA', 'JERBA', 'Autre', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I17', 'Boutique MEGRINE', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;
INSERT INTO sales.boutiques (store_id, store_name, ville, region, manager_name, active) VALUES ('I18', 'Boutique ZAHROUNI', 'TUNIS', 'Grand Tunis', '', true) ON CONFLICT (store_id) DO UPDATE SET store_name=EXCLUDED.store_name, ville=EXCLUDED.ville, region=EXCLUDED.region, manager_name=EXCLUDED.manager_name;

COMMIT;
